apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
    tier: database
type: Opaque
data:
  password: cGFzc3dvcmQ=       
  user: d29yZHBvZXJz             
  database: d29yZHBvZXJz         