apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
  labels:
    app: wordpress
    tier: frontend
type: Opaque
data:
  password: cGFzc3dvcmQ=       
  username: d29yZHBvZXJz             
  database: d29yZHBvZXJz         